platform :ios, '9.0'
use_frameworks!

target 'IndigoOmtIosLibrary_Example' do
  pod 'IndigoOmtIosLibrary', :path => '../'
  pod 'AppAuth', '~> 0.8.0', :inhibit_warnings => true
  pod 'Alamofire'
  pod 'SwiftyJSON'
  
  target 'IndigoOmtIosLibrary_UnitTests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
    pod 'Nimble', '~> 5.1.1'
    pod 'Embassy', '~> 3.1'
  end
end

target 'IndigoOmtIosLibrary_ExampleIntegration' do
    pod 'IndigoOmtIosLibrary', :path => '../'
    pod 'AppAuth', '~> 0.8.0',  :inhibit_warnings => true
    pod 'Alamofire'
    pod 'SwiftyJSON'
    
    target 'IndigoOmtIosLibrary_IntegrationTests' do
        inherit! :search_paths
        
        pod 'Quick', '~> 1.0.0'
        pod 'Nimble', '~> 5.1.1'
    end
end
