//
//  FGApplication.swift
//  IndigoOmtIosLibrary
//
//  Created by Sebastian Mamczak on 01.02.2017.
//
//

import Foundation

/// An application object.
open class FGApplication {
    
    // MARK: - properties
    
    /// The id of the application.
    public var id: String = ""
    
    /// User friendly name of the infrastructure.
    public var name: String = ""
    
    /// A verbose description of the application.
    public var applicationDescription: String = ""
    
    /// An date when the infrastructure was created.
    public var date: Date = Date(timeIntervalSince1970: 0)
    
    /// true if the infrastructure is accessible, false otherwise.
    public var enabled: Bool = false
    
    /// true if the infrastructure is virtual, false otherwise. An infrastructure is virtual if it is generated by a running task of a resource application. Default is false.
    public var virtual: Bool = false
    
    /// Parameters to access the infrastructure using SAGA. The infrastructure can be virtual, generated by an application and in this case the applications parameter is needed and it has to contain a list of application ids able to generate the infrastructure.
    public var parameters: [String] = []
    
    // MARK: - lifecycle
    
    public init() {
        
    }
    
}
